server:
  port: 9004
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'