server:
  port: 8006

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    fetch-registry: true

spring:
  application:
    name: cloud-provider-hystrix-payment