server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest
      bindings:
        output:
          destination: studyExchange #表示要使用的交换机的名字定义
          content-type: application/json #设置消息类型，文本要设置为“text/plain”
          binder: defaultRabbit #设置要绑定的消息服务的具体设置



eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: send-8801.com
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔